# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/api/*"
  to = "https://net.fucer.com.ar/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
